<?php
header("Content-Type: text/html;charset=utf-8");
date_default_timezone_set("Asia/Hong_Kong"); 
  session_start();
  include 'db.php';
  $sql="INSERT INTO music (songid, title, userid, lyricist, singer, composer, album, track, year, genre, comment, copyright, artPath, lyrics, songPath, uploadDateTime, totalPlay, totalDownload, totalShare, totalLike) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
  $songid=rand();
  $title=$_POST['title'];
  $userid=$_SESSION['uid'];
  $singer=$_POST['singer'];
  $lyricist=null;
  $composer=$_POST['composer'];
  $album=null;
  $track=1;
  $year=date("Y");
  $genre=$_POST['genre'];
  $comment=null;
  $copyright=null;
  $artPath=null;
  $lyrics=null;
  $songPath=$_POST['path'];
  $uploadDateTime=date("Y-m-d H:i:s");
  $totalPlay=0;
  $totalDownload=0;
  $totalShare=0;
  $totalLike=0;
  $stmt=mysqli_query($conn,"SET NAMES UTF8");
  $stmt=$conn->prepare($sql);
  $stmt->bind_param("isissssissssssssiiii",$songid,$title,$userid,$lyricist,$sinsinger,$composer,$album,$track,$year,$genre,$comment,$copyright,$artPath,$lyrics,$songPath,$uploadDateTime,$totalPlay,$totalDownload,$totalShare,$totalLike);
  $stmt->execute();
  printf($stmt->error);
  echo 'success';
 ?>
